version: "3.9"
services:

  cloud_drive:
    container_name: cloud_drive
    image: ksannikow/cloud_drive:${CLOUD_DRIVE_VERSION}
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Prod
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5033:80"
    volumes:
      - ./cloud_drive/https:/https
    links:
      - postgres
      - neo4j

  migrations:
    container_name: migrations
    image: ksannikow/cloud_drive_migrations:${CLOUD_DRIVE_MIGRATIONS_VERSION}
    environment:
      ASPNETCORE_ENVIRONMENT: Prod
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KLzz3Hnd
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/entrypoint-initdb:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_drive"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  neo4j:
    container_name: neo4j
    image: neo4j:4.2.3
    restart: always
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/eEzEVhn4
    ports:
      - "7474:7474"