name: 'deploy'
on:
  workflow_dispatch:
    inputs:
      cloudDriveVersion:
        description: 'cloud_drive version'
        required: true
        default: 'latest'
      cloudDriveMigrationsVersion:
        description: 'cloud_drive_migrations version'
        required: true
        default: 'latest'
    
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:

      - name: Build containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            chmod u+x create-new-containers.sh
            ./create-new-containers.sh  ${{ github.event.inputs.cloudDriveVersion }} ${{ github.event.inputs.cloudDriveMigrationsVersion }}
