# rebuild containers on remote server through ssh.

name: "ReduildContainer"
on:
  push:
    branches: ["master"]
    
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              cd ${{ secrets.PROJECT_FOLDER }};
              git checkout master;
              git pull --rebase;
              docker-compose --file docker-compose-prod.yml down --rmi local;
              docker-compose --file docker-compose-prod.yml up -d;
              docker system prune --all --force;
